# Generated by Django 5.0.6 on 2024-07-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=171)),
                ('description', models.CharField(max_length=750)),
                ('region', models.CharField(choices=[('RegionI', 'Ilocos Region'), ('RegionII', 'Cagayan Valley'), ('RegionIII', 'Central Luzon'), ('RegionIV‑A', 'CALABARZON'), ('MIMAROPA', 'MIMAROPA Region'), ('RegionV', 'Bicol Region'), ('CAR', 'Cordillera Administrative Region'), ('NCR', 'National Capital Region')], max_length=10)),
                ('author', models.CharField(max_length=157)),
                ('ingredients', models.JSONField()),
            ],
        ),
    ]
