# Generated by Django 5.0.6 on 2024-07-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipe_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='steps',
            field=models.JSONField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
